language: python
python:
  - 3.9
  - pypy
env:
  - DJANGO=">3.2"
before_install:
  - export DJANGO_SETTINGS_MODULE=jet.tests.settings
install:
  - pip install -q "Django${DJANGO}"
  - pip install .
  - pip install coverage==3.7.1
  - pip install coveralls==0.5
script:
  - coverage run --source=jet --omit=*/migrations/*,*/south_migrations/*,*/tests/* manage.py test jet
after_success:
  - coverage report
  - coveralls
matrix:
  exclude:
    - python: 3.9
      env: DJANGO=">3.2"

    - python: pypy
      env: DJANGO="<2.1"
